# Generated by Django 5.1.7 on 2025-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.CharField(default='100', max_length=10),
        ),
    ]
